list: @/plugins/muukrls/shopautumn/models/shopitem/columns.yaml

modelClass: Muukrls\Shopautumn\Models\ShopItem

title: muukrls.shopautumn::lang.menu.menu_label_items

recordUrl: muukrls/shopautumn/items/update/:id

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

defaultSort:
    column: name
    direction: asc

showCheckboxes: true

toolbar:
    buttons: list_toolbar

    search:
        prompt: backend::lang.list.search_promt
