name: Category

form: @/plugins/muukrls/shopautumn/models/category/fields.yaml

modelClass: Muukrls\Shopautumn\Models\Category

defaultRedirect: muukrls/shopautumn/categories

create:
    title: muukrls.shopautumn::lang.categories.create_title
    redirect: muukrls/shopautumn/categories/update/:id
    redirectClose: muukrls/shopautumn/categories

update:
    title: muukrls.shopautumn::lang.categories.update_title
    redirect: muukrls/shopautumn/categories/update/:id
    redirectClose: muukrls/shopautumn/categories
